### ISSUE TITLE
Issue with vincent.initialize_notebook() in Introduction

### ISSUE THREAD

**Issue by furukama** [ellisonbg/talk-2014-strata-sc#1]
Hi Brian,

in my setting (Anaconda w/Python 2.7 Vincent 0.4.2) this command throws an error:

``` ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-cb0591a990d2> in <module>()
      1 import vincent
      2 import pandas as pd
----> 3 vincent.initialize_notebook()

AttributeError: 'module' object has no attribute 'initialize_notebook'
```

Any idea on how to get it working? Could it be wrong package versions?

Benedikt

**Comment by ellisonbg** [comment]
Yes, the top level import of `initialize_notebook` just got added. In older
versions it was at `vincent.core.initialize_notebook`.

On Mon, Feb 17, 2014 at 10:16 PM, Benedikt Koehler <notifications@github.com

> wrote:
> 
> Hi Brian,
> 
> in my setting (Anaconda w/Python 2.7 Vincent 0.4.2) this command throws an
> error:
> 
> AttributeError                            Traceback (most recent call last)
> <ipython-input-5-cb0591a990d2> in <module>()
>       1 import vincent
>       2 import pandas as pd
> ----> 3 vincent.initialize_notebook()
> 
> AttributeError: 'module' object has no attribute 'initialize_notebook'
> 
> Any idea on how to get it working? Could it be wrong package versions?
> 
> Benedikt
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ellisonbg/talk-strata-sc2014/issues/1
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
I should note that you will also have to do `viz.display()` to get the plot to show up in the older version of vincent that you have.
